import React from 'react';
import Head from 'next/head';

const HeadPage = (props) => {
    return (
        <Head>
        <title>{props.title}</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
        </Head>
    );
}

export default HeadPage;
